### ISSUE TITLE
make the library thread-safe

### ISSUE THREAD

**Issue by wavenator** [brave/adblock-rust#106]
I've tried to share an instance of Engine across threads and encountered that it can not be shared across threads as it is not thread-safe. Can you please replace Rc and RefCell with Arc and RwLock/Mutex so we can use this library in threads? Thanks!

**Comment by ArniDagur** [comment]
This is also a problem for `python-adblock`. Upgrading PyO3 from `0.10` to `0.11` makes the build fail due to thread-safety issues. See https://github.com/ArniDagur/python-adblock/actions/runs/151271594.

**Comment by antonok-edm** [comment]
I don't have a good way to test this, as `adblock-rust` isn't really used in a multithreaded context in Brave. However, I would be happy to look at PRs for this.

**Comment by ArniDagur** [comment]
It's worth noting that the library used to be thread safe, but this was changed in https://github.com/brave/adblock-rust/commit/19ac71aa3670e89583ac2b764fd63b8b9b882603 for apparent performance reasons.

@AndriusA Would you be fine with reverting the aforementioned commit?

**Comment by antonok-edm** [comment]
@ArniDagur it's actually been discussed before - see https://github.com/brave/adblock-rust/issues/101#issuecomment-633961141. Ultimately it seems like the gains from thread-unsafety are more hassle than they're worth, so I would support rolling that change back.

**Comment by ArniDagur** [comment]
I'll make a PR.

**Comment by antonok-edm** [comment]
Should be fixed by #130. @wavenator if this doesn't work for you feel free to follow up.

**Comment by wavenator** [comment]
Thanks a lot for all the effort!

**Comment by ciokan** [comment]
This package is still not thread safe even with the rollback. Related discussion: https://stackoverflow.com/questions/63761408/rust-rocket-pass-variable-to-endpoints

**Comment by ArniDagur** [comment]
Yeah, you have to disable the `object-pooling` feature. That worked for me at least. Sorry for the confusion.

**Comment by ciokan** [comment]
> Yeah, you have to disable the `object-pooling` feature. That worked for me at least. Sorry for the confusion.

Can you tell me how to disable `object-pooling`? I never touched Rust before and I'm stuck here. Thank you.

**Comment by antonok-edm** [comment]
@ciokan When you add a dependency in your `Cargo.toml` file, rather than just giving a version number you can specify more information, including a list of "features". Here, you'll also want to disable default features, since `object-pooling` is on by default. This crate's supported features are all listed under `[features]` in this repo's `Cargo.toml`.

In your case you could add a new section that might look something like this:

```toml
[dependencies.adblock]
version = "0.3.2"
default-features = false
features = ["full-regex-handling", "embedded-domain-resolver"]
```

Or if you prefer, you can equivalently specify the whole dependency inline under the usual `[dependencies]` section like this:

```toml
[dependencies]
adblock = { version = "0.3.2", default-features = false, features = ["full-regex-handling", "embedded-domain-resolver"] }
```
